/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as ComprasRouteImport } from './routes/compras'
import { Route as EntradaRouteImport } from './routes/entrada'
import { Route as SaidaRouteImport } from './routes/saida'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const ComprasRoute = ComprasRouteImport.update({
  id: '/compras',
  path: '/compras',
  getParentRoute: () => rootRouteImport,
} as any)
const EntradaRoute = EntradaRouteImport.update({
  id: '/entrada',
  path: '/entrada',
  getParentRoute: () => rootRouteImport,
} as any)
const SaidaRoute = SaidaRouteImport.update({
  id: '/saida',
  path: '/saida',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/compras': typeof ComprasRoute
  '/entrada': typeof EntradaRoute
  '/saida': typeof SaidaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/compras': typeof ComprasRoute
  '/entrada': typeof EntradaRoute
  '/saida': typeof SaidaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/compras': typeof ComprasRoute
  '/entrada': typeof EntradaRoute
  '/saida': typeof SaidaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/cadastro' | '/compras' | '/entrada' | '/saida'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/cadastro' | '/compras' | '/entrada' | '/saida'
  id: '__root__' | '/' | '/cadastro' | '/compras' | '/entrada' | '/saida'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  ComprasRoute: typeof ComprasRoute
  EntradaRoute: typeof EntradaRoute
  SaidaRoute: typeof SaidaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compras': {
      id: '/compras'
      path: '/compras'
      fullPath: '/compras'
      preLoaderRoute: typeof ComprasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrada': {
      id: '/entrada'
      path: '/entrada'
      fullPath: '/entrada'
      preLoaderRoute: typeof EntradaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/saida': {
      id: '/saida'
      path: '/saida'
      fullPath: '/saida'
      preLoaderRoute: typeof SaidaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  ComprasRoute: ComprasRoute,
  EntradaRoute: EntradaRoute,
  SaidaRoute: SaidaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
